repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key

-   repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    -   id: black
        exclude: ^(src/scorebook/evaluate/_sync/|examples/)

-   repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
    -   id: autoflake
        args: [--remove-all-unused-imports, --in-place, --recursive, .]
        exclude: ^(src/scorebook/evaluate/_sync/|examples/)

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        args: ["--profile", "black"]
        exclude: ^(src/scorebook/evaluate/_sync/|examples/)

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [Flake8-pyproject, flake8-docstrings]
        args: [
            "--max-line-length=100",
            "--extend-ignore=E203",
            "--exclude=.git,__pycache__,build,dist,src/scorebook/evaluate/_sync,examples",
            "--per-file-ignores=__init__.py:F401,tests/*.py:D100,D101,D102,D103,D104"
        ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-python-dateutil, types-PyYAML]
        exclude: "(tests/.*\\.py|src/scorebook/evaluate/_sync/.*\\.py|examples/.*\\.py)"

- repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
  hooks:
    - id: detect-secrets
      args:
        - --baseline
        - .secrets.baseline
        # Ignore Jupyter auto-generated cell IDs (hex or UUID-ish)
        - --exclude-lines
        - '(?i)"id"\s*:\s*"[0-9a-f-]{8,}"'

- repo: https://github.com/gitleaks/gitleaks
  rev: v8.28.0
  hooks:
    - id: gitleaks
      args: ['--config=.gitleaks.toml']

-   repo: local
    hooks:
    -   id: generate-sync
        name: Generate sync code from async
        entry: python scripts/generate_sync.py
        language: system
        pass_filenames: false
        files: ^src/scorebook/evaluate/_async/.*\.py$
    -   id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        pass_filenames: false
        always_run: true
